### ISSUE TITLE
Support gzipped parquet files

### ISSUE THREAD

**Issue by aecorn** [statisticsnorway/datadoc#73]
```python
from datadoc import main
main("05300_statbank.parquet.gzip")
```

If parquet compression is to be disuaded from, please disregard the issue.

**Comment by mmwinther** [comment]
Internal ref: https://statistics-norway.atlassian.net/browse/STAT-187

**Comment by mmwinther** [comment]
@aecorn this is implemented and released in v0.2.4, could you test it?

**Comment by aecorn** [comment]
@mmwinther Im on version 0.2.4 trying to open parquet-files in prodsone.
Im getting a validation error
```
ValidationError: 1 validation error for DataDocVariable
short_name
  string does not match regex "[-A-Za-z0-9_.*/]" (type=value_error.str.regex; pattern=[-A-Za-z0-9_.*/])
```
There are no __DOC.json files in the folder from before.
![image](https://user-images.githubusercontent.com/20161657/214498263-6ca4e4bc-ee52-4938-bfa9-48407e4ec163.png)

This might be a new issue?

**Comment by mmwinther** [comment]
@aecorn I'm a bit late to the party here but that's an issue with the name for one of the variables (columns) in the file, it's not a problem with the file itself.
