### ISSUE TITLE
Languages-dict in json on creation

### ISSUE THREAD

**Issue by aecorn** [statisticsnorway/datadoc#75]
Certain fields have alternative language versions, in the json this is represented like:
`name: {'en': '', 'nn': '', 'no': ''}`
Though this will never be represented with all empty languages like this now, as one language must be filled in for the other languages to appear in the json? So before filling, the json just contains:
`name: None`
This might confuse people trying to operate on the json programatically.
To not be confusing for programmers I suggest that the json should contain the "empty language dictionary" listed above already at creation-time, instead of just `None`.

**Comment by mmwinther** [comment]
`None` is the correct value for unfilled fields in python.
